# Generated by Django 3.1.2 on 2020-11-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='seatlocation',
        ),
    ]
