# Generated by Django 3.1.2 on 2020-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('learning_logs', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_logs.menu_item'),
        ),
        migrations.AddField(
            model_name='order',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.row'),
        ),
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.seat'),
        ),
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.section'),
        ),
    ]
