# Generated by Django 3.1.2 on 2020-11-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20201121_2140'),
        ('customer', '0002_auto_20201121_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.entry'),
        ),
        migrations.AddField(
            model_name='order',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
    ]
