# Generated by Django 3.1.2 on 2021-02-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guest'),
        ('customer', '0003_order_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guest'),
        ),
    ]
