# Generated by Django 3.1.2 on 2020-11-23 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_seatlocation'),
        ('learning_logs', '0003_auto_20201122_1633'),
        ('customer', '0004_delete_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seatlocation',
        ),
        migrations.CreateModel(
            name='Seatlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=25)),
                ('row', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic')),
            ],
        ),
    ]
