# Generated by Django 3.1.2 on 2020-11-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20201117_2232'),
        ('customer', '0004_remove_order_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.row'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.seat'),
        ),
    ]
