# Generated by Django 3.1.2 on 2021-02-21 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guest'),
        ('customer', '0004_order_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatlocation',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.guest'),
        ),
    ]
