# Generated by Django 3.1.2 on 2021-02-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_seatlocation_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlocation',
            name='row',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seatlocation',
            name='seat',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seatlocation',
            name='section',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
