# Generated by Django 3.1.2 on 2021-03-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210221_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Received', 'Recieved'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up')], max_length=200, null=True),
        ),
    ]
