# Generated by Django 3.1.2 on 2021-01-18 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_media')),
                ('description', models.CharField(max_length=200, null=True)),
                ('section', models.CharField(max_length=50, null=True)),
                ('delivery', models.BooleanField(default=True)),
                ('pickup', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.entry')),
            ],
            options={
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('zip_code', models.IntegerField(default=33609)),
                ('city', models.CharField(default='Tampa', max_length=50)),
                ('State', models.CharField(default='Florida', max_length=50)),
                ('country', models.CharField(default='United States', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='arena_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items')),
                ('quantity', models.IntegerField(default=0)),
                ('delivery', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.menu')),
            ],
            options={
                'verbose_name_plural': 'menu items',
            },
        ),
    ]
