# Generated by Django 3.1.2 on 2020-11-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customer_seatlocation'),
        ('learning_logs', '0002_auto_20201121_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatlocation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='seatlocation',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
    ]
