# Generated by Django 3.1.2 on 2020-11-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20201114_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='venue',
            new_name='topic',
        ),
    ]
