# Generated by Django 3.1.2 on 2021-02-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20210118_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_media'),
        ),
    ]
