# Generated by Django 3.1.2 on 2021-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='logo',
        ),
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_media'),
        ),
    ]
