# Generated by Django 3.1.2 on 2021-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20210227_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
