# Generated by Django 3.1.2 on 2020-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20201025_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
