# Generated by Django 3.1.2 on 2020-12-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20201129_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
