# Generated by Django 3.1.2 on 2021-01-05 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_2053'),
        ('learning_logs', '0006_menu_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
    ]
