# Generated by Django 3.1.2 on 2021-01-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20210104_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='pickup',
            field=models.BooleanField(default=True),
        ),
    ]
