# Generated by Django 3.1.2 on 2020-11-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20201104_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='price',
        ),
    ]
