# Generated by Django 3.1.2 on 2020-11-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_auto_20201104_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'menus'},
        ),
        migrations.AlterModelOptions(
            name='menu_item',
            options={'verbose_name_plural': 'menu items'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant',
            new_name='entry',
        ),
    ]
