# Generated by Django 3.1.2 on 2020-11-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_auto_20201106_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
