# Generated by Django 3.1.2 on 2020-11-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_auto_20201106_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items'),
        ),
    ]
