# Generated by Django 3.1.2 on 2020-11-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_menu_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
